export const types = {
    // Get list Movies
    GET_LIST_POPULAR_MOVIES: "GET_LIST_POPULAR_MOVIES",
    GET_LIST_POPULAR_MOVIES_SUCCESS: "GET_LIST_POPULAR_MOVIES_SUCCESS",
    GET_LIST_TOPRATE_MOVIES: "GET_LIST_TOPRATE_MOVIES",
    GET_LIST_TOPRATE_MOVIES_SUCCESS: "GET_LIST_TOPRATE_MOVIES_SUCCESS",
    GET_LIST_UPCOMING_MOVIES: "GET_LIST_UPCOMING_MOVIES",
    GET_LIST_UPCOMING_MOVIES_SUCCESS: "GET_LIST_UPCOMING_MOVIES_SUCCESS",


    // Get detail a movie
    GET_VIDEOS: "GET_VIDEOS",
    GET_VIDEOS_SUCCESS: "GET_VIDEOS_SUCCESS",
};