export const types = {
    GET_LIST_POPULAR_MOVIES: "GET_LIST_POPULAR_MOVIES",
    GET_LIST_POPULAR_MOVIES_SUCCESS: "GET_LIST_POPULAR_MOVIES_SUCCESS",
    GET_LIST_TOPRATE_MOVIES: "GET_LIST_TOPRATE_MOVIES",
    GET_LIST_TOPRATE_MOVIES_SUCCESS: "GET_LIST_TOPRATE_MOVIES_SUCCESS",
    GET_LIST_UPCOMING_MOVIES: "GET_LIST_UPCOMING_MOVIES",
    GET_LIST_UPCOMING_MOVIES_SUCCESS: "GET_LIST_UPCOMING_MOVIES_SUCCESS",
};