export const types = {
    // Get list Movies
    GET_LIST_POPULAR_MOVIES: "GET_LIST_POPULAR_MOVIES",
    GET_LIST_POPULAR_MOVIES_SUCCESS: "GET_LIST_POPULAR_MOVIES_SUCCESS",
    GET_LIST_TOPRATE_MOVIES: "GET_LIST_TOPRATE_MOVIES",
    GET_LIST_TOPRATE_MOVIES_SUCCESS: "GET_LIST_TOPRATE_MOVIES_SUCCESS",
    GET_LIST_UPCOMING_MOVIES: "GET_LIST_UPCOMING_MOVIES",
    GET_LIST_UPCOMING_MOVIES_SUCCESS: "GET_LIST_UPCOMING_MOVIES_SUCCESS",


    // Get detail a movie
    GET_VIDEO_MOVIE: "GET_VIDEO_MOVIE",
    GET_VIDEO_MOVIE_SUCCESS: "GET_VIDEO_MOVIE_SUCCESS",

    GET_VIDEOS_MOVIE: "GET_VIDEOS_MOVIE",
    GET_VIDEOS_MOVIE_SUCCESS: "GET_VIDEOS_MOVIE_SUCCESS",

    GET_INFO_MOVIE: "GET_INFO_MOVIE",
    GET_INFO_MOVIE_SUCCESS: "GET_INFO_MOVIE_SUCCESS",

    GET_CREDITS_MOVIE: "GET_CREDITS_MOVIE",
    GET_CREDITS_MOVIE_SUCCESS: "GET_CREDITS_MOVIE_SUCCESS",
};